In [1]:
import pandas as pd
import bigml.api
from pprint import pprint
api = bigml.api.BigML()

In [2]:
training_df = pd.read_csv('./datasets/cs-training.csv')
test_df = pd.read_csv('./datasets/cs-test.csv')

dataframes = [training_df, test_df]

In [3]:
for df in dataframes:
    df.columns.values[0]="Id"
    df[['MonthlyIncome','NumberOfDependents']] = df[['MonthlyIncome','NumberOfDependents']].fillna(0)
    df['NumberOfTimes30DaysOrMoreLate'] = df['NumberOfTime30-59DaysPastDueNotWorse']+df['NumberOfTime60-89DaysPastDueNotWorse']+df['NumberOfTimes90DaysLate']
    df['IncomePerPerson'] = df['MonthlyIncome']/(df['NumberOfDependents']+1)
    df['MonthlyDebt'] = df['MonthlyIncome']*df['DebtRatio']
    df['MonthlyBalance'] = df['MonthlyIncome']-df['MonthlyDebt']

In [4]:
training_df.to_csv('./results2/full_train_modif.csv', index=False)
test_df.to_csv('./results2/test_modif.csv', index=False)

In [9]:
full_train_source = api.create_source('./results2/full_train_modif.csv')
api.ok(full_train_source)

True

In [10]:
full_train_dataset = api.create_dataset(full_train_source)
api.ok(full_train_dataset)

True

In [11]:
dataset_train80 = api.create_dataset(full_train_dataset,{"name":"Train", "sample_rate":0.8, "seed":"my seed"})
api.ok(dataset_train80)

True

In [12]:
dataset_valid20 = api.create_dataset(full_train_dataset, {"name":"Validation", "sample_rate":0.8, "seed":"my seed", "out_of_bag":True})
api.ok(dataset_valid20)

True

In [13]:
ensemble = api.create_ensemble(dataset_train80, {"objective_field":"SeriousDlqin2yrs"})
api.ok(ensemble)

True

In [ ]:
test_source = api.create_source('./results2/test_modif.csv')
api.ok(test_source)

In [ ]:
test_dataset = api.create_dataset(test_source)
api.ok(test_dataset)

In [15]:
batch_prediction = api.create_batch_prediction(ensemble, dataset_valid20, {'all_fields':True, 'probabilities':True})
api.ok(batch_prediction)

True

In [17]:
api.download_batch_prediction(batch_prediction, filename= './results2/my_predictions.csv')

'./results2/my_predictions.csv'

In [19]:
batch_prediction_df = pd.read_csv('./results2/my_predictions.csv', index_col=0)
batch_prediction_df

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,NumberOfTimes30DaysOrMoreLate,IncomePerPerson,MonthlyDebt,MonthlyBalance,SeriousDlqin2yrs.1,0 probability,1 probability
Id,,,,,,,,,,,,,,,,,,
5,0,0.907239,49,1,0.024926,63588,7,0,1,0,0,1,63588.0,1584.975094,62003.024906,0,0.80812,0.19188
20,0,0.602794,25,0,0.065868,333,2,0,0,0,0,0,333.0,21.934132,311.065868,0,0.95190,0.04810
27,0,0.052436,58,0,0.097672,8333,22,0,1,0,0,0,8333.0,813.902326,7519.097674,0,0.98847,0.01153
28,0,0.034421,69,0,0.042383,2500,17,0,0,0,1,0,1250.0,105.957617,2394.042382,0,0.99378,0.00622
31,0,0.704074,28,1,0.155201,4200,8,0,0,0,0,1,4200.0,651.844801,3548.155199,0,0.86387,0.13613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149964,0,0.230353,61,0,883.000000,0,15,0,0,0,2,0,0.0,0.000000,0.000000,0,0.98434,0.01566
149972,0,0.058001,83,0,0.013997,5000,6,0,0,0,0,0,5000.0,69.986005,4930.013995,0,0.99570,0.00430
149976,0,0.022088,58,0,2716.000000,0,8,0,2,0,0,0,0.0,0.000000,0.000000,0,0.99373,0.00627
149986,0,0.954409,26,0,0.324962,1950,4,0,0,0,0,0,1950.0,633.675038,1316.324962,0,0.91415,0.08585
149998,0,0.246044,58,0,3870.000000,0,18,0,1,0,0,0,0.0,0.000000,0.000000,0,0.98615,0.01385

In [63]:
def error(row):
    if (row['SeriousDlqin2yrs'] == row['SeriousDlqin2yrs.1'] and row['SeriousDlqin2yrs'] == 0):
        row['error'] = 'TN'
    elif (row['SeriousDlqin2yrs'] == row['SeriousDlqin2yrs.1'] and row['SeriousDlqin2yrs'] == 1):
        row['error'] = 'TP'
    elif row['SeriousDlqin2yrs'] > row['SeriousDlqin2yrs.1']:
        row['error'] = 'FN'
    else:
        row['error'] = 'FP'
    return row['error']

batch_prediction_df['error'] = batch_prediction_df.apply(error, axis=1)
batch_prediction_df

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,NumberOfTimes30DaysOrMoreLate,IncomePerPerson,MonthlyDebt,MonthlyBalance,SeriousDlqin2yrs.1,0 probability,1 probability,error
Id,,,,,,,,,,,,,,,,,,,
5,0,0.907239,49,1,0.024926,63588,7,0,1,0,0,1,63588.0,1584.975094,62003.024906,0,0.80812,0.19188,TN
20,0,0.602794,25,0,0.065868,333,2,0,0,0,0,0,333.0,21.934132,311.065868,0,0.95190,0.04810,TN
27,0,0.052436,58,0,0.097672,8333,22,0,1,0,0,0,8333.0,813.902326,7519.097674,0,0.98847,0.01153,TN
28,0,0.034421,69,0,0.042383,2500,17,0,0,0,1,0,1250.0,105.957617,2394.042382,0,0.99378,0.00622,TN
31,0,0.704074,28,1,0.155201,4200,8,0,0,0,0,1,4200.0,651.844801,3548.155199,0,0.86387,0.13613,TN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149964,0,0.230353,61,0,883.000000,0,15,0,0,0,2,0,0.0,0.000000,0.000000,0,0.98434,0.01566,TN
149972,0,0.058001,83,0,0.013997,5000,6,0,0,0,0,0,5000.0,69.986005,4930.013995,0,0.99570,0.00430,TN
149976,0,0.022088,58,0,2716.000000,0,8,0,2,0,0,0,0.0,0.000000,0.000000,0,0.99373,0.00627,TN
149986,0,0.954409,26,0,0.324962,1950,4,0,0,0,0,0,1950.0,633.675038,1316.324962,0,0.91415,0.08585,TN
149998,0,0.246044,58,0,3870.000000,0,18,0,1,0,0,0,0.0,0.000000,0.000000,0,0.98615,0.01385,TN

In [69]:
bp_df_classified = batch_prediction_df.sort_values(by=['error','1 probability'], ascending=[True, True])
bp_df_classified

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,NumberOfTimes30DaysOrMoreLate,IncomePerPerson,MonthlyDebt,MonthlyBalance,SeriousDlqin2yrs.1,0 probability,1 probability,error
Id,,,,,,,,,,,,,,,,,,,
89493,0,0.001395,80,0,0.000000,2232,1,0,0,0,0,0,2232.0,0.000000,2232.000000,0,0.99836,0.00164,TN
84690,0,0.103388,74,0,0.001238,2422,2,0,0,0,0,0,2422.0,2.998763,2419.001237,0,0.99826,0.00174,TN
22160,0,0.004461,74,0,0.000400,2500,1,0,0,0,0,0,2500.0,0.999600,2499.000400,0,0.99814,0.00187,TN
44820,0,0.005999,80,0,0.151240,1652,2,0,0,0,0,0,1652.0,249.848759,1402.151241,0,0.99814,0.00187,TN
48840,0,0.014466,74,0,0.082187,3053,2,0,0,0,0,0,3053.0,250.917812,2802.082188,0,0.99814,0.00187,TN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96783,1,1.904431,49,3,548.000000,0,5,2,0,2,0,7,0.0,0.000000,0.000000,1,0.27645,0.72355,TP
94474,1,0.998546,44,2,0.640236,10000,12,4,2,0,3,6,2500.0,6402.359760,3597.640240,1,0.27464,0.72536,TP
116004,0,1.680710,51,1,0.178730,3384,7,2,0,3,1,6,1692.0,604.821271,2779.178729,1,0.26795,0.73205,FP
138852,1,0.973401,47,0,1.413593,16566,6,10,2,2,2,12,5522.0,23417.586409,-6851.586409,1,0.26614,0.73386,TP
103403,1,1.610556,45,1,0.207701,2700,3,4,0,1,2,6,900.0,560.792300,2139.207700,1,0.25904,0.74097,TP

In [ ]:
evaluation = api.create_evaluation(ensemble, dataset_valid20)
api.ok(evaluation)

In [ ]:
my_prediction_df = pd.read_csv('./results2/my_predictions.csv', index_col = 0)
my_prediction_df

In [ ]:
my_prediction_df.to_csv('./results2/prediction-kaggle.csv')

In [ ]:
matrice_confusion = evaluation['object']['result']['model']['confusion_matrix']
matrice_conf_df = pd.DataFrame(matrice_confusion, columns={'P','N'}, index={'P','N'})
pprint(matrice_conf_df)

In [ ]:
auc = evaluation['object']['result']['model']['average_area_under_roc_curve']
pprint(auc)

In [ ]:
import kaggle
#kaggle.api.competition_submit("./results/prediction-kaggle.csv", "BigML ensemble", "GiveMeSomeCredit")